/**
 * 
 */
package com.manning.sbia.ch06.file;

import java.io.IOException;
import java.io.Writer;

import org.springframework.batch.item.file.FlatFileHeaderCallback;

/**
 * @author bazoud
 *
 */
public class ProductHeaderCallback implements FlatFileHeaderCallback {

    @Override
    public void writeHeader(Writer writer) throws IOException {
        writer.write("# Generated by FlatFileHeaderCallback");
    }

}
