insert into partner_mapping (partner_id,partner_product_id,store_product_id) values ('PARTNER1','211','PR....211');
insert into partner_mapping (partner_id,partner_product_id,store_product_id) values ('PARTNER1','212','PR....212');
insert into partner_mapping (partner_id,partner_product_id,store_product_id) values ('PARTNER1','213','PR....213');
insert into partner_mapping (partner_id,partner_product_id,store_product_id) values ('PARTNER1','214','PR....214');
insert into partner_mapping (partner_id,partner_product_id,store_product_id) values ('PARTNER1','215','PR....215');
insert into partner_mapping (partner_id,partner_product_id,store_product_id) values ('PARTNER1','216','PR....216');
insert into partner_mapping (partner_id,partner_product_id,store_product_id) values ('PARTNER1','217','PR....217');
insert into partner_mapping (partner_id,partner_product_id,store_product_id) values ('PARTNER1','218','PR....218');
insert into partner_mapping (partner_id,partner_product_id,store_product_id) values ('PARTNER1','219','PR....219');