
DELETE FROM PRODUCT;
INSERT INTO PRODUCT (ID, NAME, DESCRIPTION, PRICE) VALUES ('PR....211', 'Sony Ericsson W810i', '', 139.45);
INSERT INTO PRODUCT (ID, NAME, DESCRIPTION, PRICE) VALUES ('PR....212', 'Samsung MM-A900M Ace', '', 97.80);
